### ISSUE TITLE
Components using incorrect styles

### ISSUE THREAD

**Issue by darkmantle** [Notalib/nativescript-accessibility-ext#16]
There is an issue that when I am using the CSS code within my component SCSS file, it is applying style to all other components as well.

I am using NS 5.1.1 with 5.0.0-alpha.1 and this is the only issue I am getting. Is there a way around this?

**Comment by m-abs** [comment]
Hi @darkmantle, 

Thank you for your bug rapport.

Unfortunately I'm not sure I understand what you're trying to do.

Are you importing the `@nota/nativescript-accessibility-ext/css/a11y` stylesheet into a component style-sheet?
Those are meant to be used in the app-wide style-sheet as an extension to the `nativescript-theme`.

It might help me to understand the issue, if you could provide a simple example?

**Comment by darkmantle** [comment]
Hi @m-abs 

This is an example of my component styles:

`@import '~@nota/nativescript-accessibility-ext/scss/fontscales';

@each $scale, $params in $a11y-font-scales {
  	$factor: map-get($params, factor);

  	/deep/ Page.a11y-fontscale-#{$scale} {
		.pill {
			color: #2A435A;
			padding: 8 12 8 12;
			height: 40;
			border-bottom-width: 2;
			border-bottom-color: #D7E3F0;
			font-size: 14 * $factor;
		}
	}
}`

If I do that, then all labels with class "pill", even in other components, have the styles applied to them.

If I apply a class on the components root layout and wrap that class around my custom CSS it works fine, naturally, but I am not sure if this is how you intended or the instructions are outdates.

**Comment by m-abs** [comment]
I see the problem...

It is a consequence of `/deep/`. It works around angular's ViewEncapsulation so the styling applies to all components.

We need a better way to do this, I'll have to think about it.

For now you can work around the problem by using a unique class-name in your component.

**Comment by m-abs** [comment]
Hi @darkmantle, 

Could you try this:
```scss
@import '~@nota/nativescript-accessibility-ext/scss/fontscales';

@each $scale, $params in $a11y-font-scales {
  	$factor: map-get($params, factor);

         Page.a11y-fontscale-#{$scale} :host {
		.pill {
			color: #2A435A;
			padding: 8 12 8 12;
			height: 40;
			border-bottom-width: 2;
			border-bottom-color: #D7E3F0;
			font-size: 14 * $factor;
		}
	}
}

```
