### ISSUE TITLE
feature: CSS-classes for fontscale

### ISSUE THREAD

**Issue by m-abs** [Notalib/nativescript-accessibility-ext#8]
Create default CSS-classes for font scaling.

[nativescript-theme-core](https://github.com/NativeScript/theme) provides a number of CSS-classes for things like font-size.
```css
.t-10 {
    font-size: 10
}

....

.t-30 {
    font-size: 30
}
```

We should provide css for iOS font-scaling (NOT Android since they do it automatically), like these
```css
Page.a11y-fontscale-150 .t-10 {
   font-size: 15;
}

...

Page.a11y-fontscale-150 .t-30 {
   font-size: 45;
}
```
